import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Suspense } from "react";
import Loading from "./Loading";

const inter = Inter({ subsets: ["latin"] });
const ibm = IBM_Plex_Sans({subsets: ['latin'], weight: "300"})

export const metadata: Metadata = {
  //#F8FAFC
  title: "Planner",
  description: "Generated by create next app",
  icons: {
    icon: ['/nuevoIcono.jpg?v=4']
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className={`${ibm.className} pt-16 lg:pt-12`}>
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          //pauseOnFocusLoss
          draggable
          //pauseOnHover
          theme="light"
        />
          <Suspense fallback={<Loading />}>
            {children}  
          </Suspense>            
        <ToastContainer/>
      </body>
    </html>
  );
}
